### ISSUE TITLE
unable to prepare context: unable to evaluate symlinks in Dockerfile path

### ISSUE THREAD

**Issue by kjplunkett** [aws-actions/amazon-ecs-deploy-task-definition#1]
I was just following along with the tutorial here:
https://aws.amazon.com/blogs/opensource/github-actions-aws-fargate/

I seem to be running into an error on the build tag and push step, everything before is working. I have not pushed a new container image to ECR before so it could be something I don't understand about how that works but it appears the dockerfile does not exist? 

![image](https://user-images.githubusercontent.com/10409809/68988361-a71b6e80-07fb-11ea-9ba1-65bfbd39705e.png)

console output for this step:
```bash
 # Build a docker container and
  # Build a docker container and
  # push it to ECR so that it can
  # be deployed to ECS.
  docker build -t $ECR_REGISTRY/$ECR_REPOSITORY:$IMAGE_TAG .
  docker push $ECR_REGISTRY/$ECR_REPOSITORY:$IMAGE_TAG
  echo "::set-output name=image::$ECR_REGISTRY/$ECR_REPOSITORY:$IMAGE_TAG"
  shell: /bin/bash -e {0}
  env:
    AWS_ACCESS_KEY_ID: ***
    AWS_SECRET_ACCESS_KEY: ***
    AWS_DEFAULT_REGION: us-east-1
    AWS_REGION: us-east-1
    ECR_REGISTRY: ***.dkr.ecr.us-east-1.amazonaws.com
    ECR_REPOSITORY: my-ecr-repo
    IMAGE_TAG: 0653508e9470c725335afc5a5c61667211fe9cc8
unable to prepare context: unable to evaluate symlinks in Dockerfile path: lstat /home/runner/work/FargateActionDemo/FargateActionDemo/Dockerfile: no such file or directory
##[error]Process completed with exit code 1.
```

**Comment by lukasgjetting** [comment]
@kjplunkett Did you solve this?

If so, do you remember how?

**Comment by kjplunkett** [comment]
Yes I made a rookie mistake...didn't have a Dockerfile in my repo at this point so naturally this error arose:
```
unable to prepare context: unable to evaluate symlinks in Dockerfile path:
```

**Comment by dhanarajknp** [comment]
can i have the docker sample file here

**Comment by kjplunkett** [comment]
> @kjplunkett Did you solve this?
> 
> If so, do you remember how?

I didn't have a docker file in the project 🤦  - see https://github.com/aws-actions/amazon-ecs-deploy-task-definition/issues/1#issuecomment-581498002

**Comment by dhanarajknp** [comment]
(root directory name)
    |-- buildspec.yml
    `-- Dockerfile

Below sample Dockerfile
===========
FROM golang:1.12-alpine AS build
#Install git
RUN apk add --no-cache git
#Get the hello world package from a GitHub repository
RUN go get github.com/golang/example/hello
WORKDIR /go/src/github.com/golang/example/hello
# Build the project and send the output to /bin/HelloWorld 
RUN go build -o /bin/HelloWorld

FROM golang:1.12-alpine
#Copy the build's output binary from the previous build container
COPY --from=build /bin/HelloWorld /bin/HelloWorld
ENTRYPOINT ["/bin/HelloWorld"]
