### ISSUE TITLE
Does not stop an existing task

### ISSUE THREAD

**Issue by theogravity** [aws-actions/amazon-ecs-deploy-task-definition#113]
If I had not noticed this, the action would have waited forever, burning my action credits.

`service xxx was unable to place a task because no container instance met all of its requirements. The closest matching container-instance xxx is already using a port required by your task. For more information, see the Troubleshooting section.`

Is there a way to kill the existing task that it would be replacing first?

I also manually stopped the task and it deployed out, but the action kept on spinning like it was still waiting for a status update.

**Comment by JeffJassky** [comment]
I need something similar. Ideally, it would replace any existing task on the service - or stop other tasks on the service once it starts successfully.

My use case is keeping a staging environment up to date when new code is pushed.

**Comment by mding5692** [comment]
Yep this would be important for me too, much thanks!

**Comment by mding5692** [comment]
Think this can be closed now

**Comment by allisaurus** [comment]
@mding5692 @theogravity forcing a new deployment will cycle the tasks, but will not result in the old tasks being killed prior to new ones starting if your [deployment configuration](https://docs.aws.amazon.com/AmazonECS/latest/APIReference/API_DeploymentConfiguration.html) has a (default) `minimumHealthyPercent` of 100%. 

So if your service is running and consuming all the resources available in your cluster (we're talking EC2 launch type, as per above error msg), then the service will try to start a new task _first_ and that will fail b/c there's no more capacity. Lowering the `minimumHealthyPercent` will allow existing tasks to be killed prior to new ones starting (see link for more info)

**Comment by mding5692** [comment]
> @mding5692 @theogravity forcing a new deployment will cycle the tasks, but will not result in the old tasks being killed prior to new ones starting if your [deployment configuration](https://docs.aws.amazon.com/AmazonECS/latest/APIReference/API_DeploymentConfiguration.html) has a (default) `minimumHealthyPercent` of 100%.
> 
> So if your service is running and consuming all the resources available in your cluster (we're talking EC2 launch type, as per above error msg), then the service will try to start a new task _first_ and that will fail b/c there's no more capacity. Lowering the `minimumHealthyPercent` will allow existing tasks to be killed prior to new ones starting (see link for more info)

Ok will try that, much thanks

**Comment by theogravity** [comment]
@allisaurus Thanks, that makes a lot of sense.

Wonder if this is something that should be added to the readme.
