### ISSUE TITLE
Expected params.forceNewDeployment to be a boolean

### ISSUE THREAD

**Issue by dili91** [aws-actions/amazon-ecs-deploy-task-definition#157]
Is this issue solved ? i'm still getting that with 1.4.1. 

```
Run aws-actions/amazon-ecs-deploy-task-definition@v1.4.1
  with:
    task-definition: /home/runner/work/_temp/task-definition--435-nD4dXDjs371k-.json
    cluster: ef-stg-cluster
    service: ef-stg-service
    force-new-deployment: true
  env:
    AWS_DEFAULT_REGION: ***
    AWS_REGION: ***
    AWS_ACCESS_KEY_ID: ***
    AWS_SECRET_ACCESS_KEY: ***
Error: Expected params.forceNewDeployment to be a boolean
```

**Comment by varnitgoyal1** [comment]
pr 140 fixed it then the bug returned, please help fix it

**Comment by dili91** [comment]
thanks @yehuda-elementryx ! 
looking forward to a new release 🙏

**Comment by atellezsazo** [comment]
@yehuda-elementryx! I tried your fork, it's still having the problem :(

**Comment by yehuda-elementryx** [comment]
Hi @atellezsazo what does your config look like? I unit tested with `force-new-deployment: 'true'` with the quotation marks to make it a string, but not sure that my test was comprehensive. I definitely didn't test with force-new-deployment having a boolean value.

**Comment by dili91** [comment]
As suggested on the PR itself, I'd keep it simple and accept only boolean values there :)

**Comment by kaka-ruto** [comment]
Having the same issue. Looking forward to the release.

**Comment by piradeepk** [comment]
Closing as this was released yesterday (02/08)
