### ISSUE TITLE
Question: Is there an equivalent action for AWS EKS? 

### ISSUE THREAD

**Issue by nskrjabins** [aws-actions/amazon-ecs-deploy-task-definition#171]
Is there an equivalent action for AWS EKS?

**Comment by paragbhingre** [comment]
@nskrjabins Thank you for your question. 
Unfortunately, there isn't any equivalent action for AWS EKS.

**Comment by paragbhingre** [comment]
@nskrjabins I hope we addressed your concern, I'm closing this issue for now. If you have any more queries then feel free to get back to us.

**Comment by nskrjabins** [comment]
Sure, no worries at all.
