### ISSUE TITLE
Question : For a Service running with multiple tasks inside different instances

### ISSUE THREAD

**Issue by aritranagnordcloud** [aws-actions/amazon-ecs-deploy-task-definition#179]
When we have multiple instances and more than 1 tasks with ECS Classic Configuration. 
The Actions are unable to deploy to propagate the tasks to all the instances and trying to deploy all the tasks in one container. 
which results in the error "already using a port required by your task." and "was unable to place a task because no container instance met all of its requirements"

Do we have any fix for this scenario?

**Comment by paragbhingre** [comment]
@aritranagnordcloud, Thank you for your question May I know if you are using [Dynamic Port Mappings](https://aws.amazon.com/premiumsupport/knowledge-center/dynamic-port-mapping-ecs/)?

**Comment by aritranagnordcloud** [comment]
Hi, Yes with the dynamic port mapping.
