### ISSUE TITLE
Cannot read property 'type' of null

### ISSUE THREAD

**Issue by mfboulos** [aws-actions/amazon-ecs-deploy-task-definition#2]
Followed all steps of the deployment process outlined in the default Github Actions yml. This step always ends in a null pointer exception, and since `index.js` is so massive, it's hard to debug anything. The error is also only as verbose as the title, no stacktrace, line numbers, anything.

**Comment by clareliguori** [comment]
Thanks for trying this out! To narrow down where the error is happening, can you create a secret named ACTIONS_STEP_DEBUG with the value 'true' to see the debug messages in your action logs?

**Comment by mfboulos** [comment]
I've been spending the last half day or so trying to narrow it down. It might have something to do with how validation or serialization functions handle `null` fields on structure shapes.

The task definition I'm using came straight from my ECS on the AWS console, but I'm realizing that it's actually the response AWS sends back from a task definition since there are a few extra fields. It also had a lot of `null` fields, so I removed those and the extras that weren't expected, and now here's where I'm at:

```
##[debug]Evaluating condition for step: 'Deploy Amazon ECS task definition'
##[debug]Parsing expression: <success()>
##[debug]Evaluating: success()
##[debug]Evaluating success:
##[debug]=> true
##[debug]Result: true
##[debug]Starting: Deploy Amazon ECS task definition
##[debug]Loading inputs
##[debug]Evaluating: steps.task-def.outputs.task-definition
##[debug]Evaluating Index:
##[debug]..Evaluating Index:
##[debug]....Evaluating Index:
##[debug]......Evaluating steps:
##[debug]......=> Object
##[debug]......Evaluating String:
##[debug]......=> 'task-def'
##[debug]....=> Object
##[debug]....Evaluating String:
##[debug]....=> 'outputs'
##[debug]..=> Object
##[debug]..Evaluating String:
##[debug]..=> 'task-definition'
##[debug]=> '/home/runner/work/_temp/task-definition-27961zBZiXxjdRic.json'
##[debug]Result: '/home/runner/work/_temp/task-definition-27961zBZiXxjdRic.json'
##[debug]Loading env
Run aws-actions/amazon-ecs-deploy-task-definition@v1
  with:
    task-definition: /home/runner/work/_temp/task-definition-27961zBZiXxjdRic.json
    service: ob-service
    cluster: ob-cluster
    wait-for-service-stability: true
  env:
    AWS_ACCESS_KEY_ID: ***
    AWS_SECRET_ACCESS_KEY: ***
    AWS_DEFAULT_REGION: us-west-1
    AWS_REGION: us-west-1
##[debug]Registering the task definition
::set-output name=task-definition-arn,::arn:aws:ecs:us-west-1:***:task-definition/ob-task-definition:4
##[debug]='arn:aws:ecs:us-west-1:***:task-definition/ob-task-definition:4'
##[debug]Updating the service
##[debug]Waiting for the service to become stable
##[error]Resource is not in the state servicesStable
##[error]Node run failed with exit code 1
##[debug]Finishing: Deploy Amazon ECS task definition
```

I'm a bit new to ECS and configuring IAM users for minimum permissions and such. Is there a particular way to retrieve the task definition I need?

**Comment by clareliguori** [comment]
There is not an API that will give you the task definition in the input format.  This command will generate the skeleton to start off with:
`aws ecs register-task-definition --generate-cli-skeleton > task-definition.json`

Based on the logs above, it looks like you're now able to register the task definition but ECS is not able to start your containers.  For next steps, I would suggest looking at the service in the ECS console, going to Tasks -> Stopped to see why the containers are dying.

**Comment by mfboulos** [comment]
Got it, thanks! After a few more iterations, I found that I just had to pass an environment variable to the container. It's still failing the same way though, telling me the service isn't stable, which is definitely weird considering the container is built correctly now.

**Comment by clareliguori** [comment]
Interesting, the state "services stable" is defined here:
https://github.com/aws/aws-sdk-js/blob/cc29728c1c4178969ebabe3bbe6b6f3159436394/apis/ecs-2014-11-13.waiters2.json#L42-L72

It calls DescribeServices (`aws ecs describe-services --service xyz`) and checks that:
* service isn't missing
* service isn't draining or inactive
* service has a single deployment
* service running count == service desired count

**Comment by mfboulos** [comment]
So I triggered a deployment and tracked every step to deployment. Here's what I found:
* The GHA script only waits a couple seconds to error out, even with `wait-for-service-stability: true`
* The service deployed to is the only service in the cluster, and it's active
* The service has a single deployment

I took a look at the event logs in the service, and found this too:
```
2019-11-17 12:43:39 -0800
service ob-service has started 1 tasks: task d0bbf143-4308-4c3f-ac1f-a7fc2b9f7b13.
```

followed by

```
2019-11-17 12:44:21 -0800
service ob-service has reached a steady state.
```

So I think ultimately the script is getting impatient waiting for stability. That issue, however, is largely unrelated to what I initially wrote this issue for. Should I open a new one to track this?

**Comment by clareliguori** [comment]
Yeah, please open a separate issue.

If you're able to reproduce the initial issue, I have some additional debugging turned on in my fork that should give us a stacktrace:
```
    - name: Deploy Amazon ECS task definition
      uses: clareliguori/amazon-ecs-deploy-task-definition@master
      with:
        task-definition: ${{ steps.task-def.outputs.task-definition }}
        service: sample-app-service
        cluster: default
        wait-for-service-stability: true
```
