### ISSUE TITLE
Just force a new deployment 

### ISSUE THREAD

**Issue by jfrolich** [aws-actions/amazon-ecs-deploy-task-definition#21]
I don't want to store the task-definition.json in my repo, and the task definition is not changing for a deploy anyway because the tag is stable (production/staging).

It would be great to have an action to just restart the service as per the following command:

```
ecs update-service --cluster ff_prod --service ff_prod --force-new-deployment
```

The actions/aws-cli is deprecated, but is it going to be replaced with an action that provides the full power of the cli?

**Comment by clareliguori** [comment]
Hello, I have opened an issue on the aws-cli to track that: https://github.com/aws/aws-cli/issues/4835

Note that the AWS CLI is pre-installed in the GitHub-hosted environments. For example, `runs-on: ubuntu-latest` will have AWS CLI version 1.16.299, and you can do the following:
```
  - name: Force deployment
    run: |
      aws ecs update-service --cluster ff_prod --service ff_prod --force-new-deployment
```
