### ISSUE TITLE
* UnexpectedParameter: Unexpected key <name> errors

### ISSUE THREAD

**Issue by edgarrc** [aws-actions/amazon-ecs-deploy-task-definition#22]
Workflow created using [ suggested AWS actions/starter-workflows](https://github.com/actions/starter-workflows/blob/master/ci/aws.yml)

On this step:

```
    - name: Fill in the new image ID in the Amazon ECS task definition
      id: task-def
      uses: aws-actions/amazon-ecs-render-task-definition@v1
      with:
        task-definition: task-definition.json
        container-name: sample-app
        image: ${{ steps.build-image.outputs.image }}
```

I replaced the version to the last version

```
      uses: aws-actions/amazon-ecs-deploy-task-definition@v1.0.1
```

and I have the task-definition.json file on repository correctly (copied from json tab, this step works fine)

But on the following step, that uses amazon-ecs-deploy-task-definition, I get this error:

```
 Deploy Amazon ECS task definition0s
##[error]Node run failed with exit code 1
Run aws-actions/amazon-ecs-deploy-task-definition@v1.0.1
##[error]There were 5 validation errors:
* UnexpectedParameter: Unexpected key 'compatibilities' found in params
* UnexpectedParameter: Unexpected key 'taskDefinitionArn' found in params
* UnexpectedParameter: Unexpected key 'requiresAttributes' found in params
* UnexpectedParameter: Unexpected key 'revision' found in params
* UnexpectedParameter: Unexpected key 'status' found in params
##[error]Node run failed with exit code 1
```

This template uses ubuntu-latest, so I tried to update the awscli at the beginning

```
    steps:
    - name: Update
      run: |
        pip install wheel
        pip install --upgrade awscli
```
Got successfully executed:

```
Successfully installed awscli-1.17.0
```

But the error persists.

**Comment by clareliguori** [comment]
Hi, what is shown in the ECS console JSON tab is the output of the DescribeTaskDefinition API, which has those extra attributes.  They are not valid inputs to RegisterTaskDefinition, so just remove them from your repo's file and the action should succeed.

**Comment by edgarrc** [comment]
Thanks, I wasn't sure if I could remove the "requiresAttributes", but it worked perfectly. Thanks!

**Comment by tovbinm** [comment]
I would it handy to remove the offensive properties with `jq` as follows:
```bash
aws ecs describe-task-definition --task-definition my-task-definition --query taskDefinition | jq 'del(.compatibilities,.taskDefinitionArn,.requiresAttributes,.revision,.status)'
```
