### ISSUE TITLE
DockerTimeoutError: ECS Task definition run on EC2 Windows cluster

### ISSUE THREAD

**Issue by carthic1** [aws-actions/amazon-ecs-deploy-task-definition#232]
Receiving STOPPED (DockerTimeoutError: Could not tranisition to started; timed out after waiting 8m0s) error while running an ECS Task definition on an EC2 Windows + Networking cluster. I couldn't find any aws documentation for this error for EC2 Windows cluster. 

I am not sure if this is the right forum for me to submit this issue, but I had tried several things and I kind of reached a dead-end on this, hence posting it here as a last resort. Could you please help with a resolution on this.

**Comment by allisaurus** [comment]
Hi @carthic1 - that error typically means there's a networking configuration issue. That leaves a lot of room for different things to have gone wrong, so I can't zero in on any specific guidance but you may want to review the [ECS networking best practices](https://docs.aws.amazon.com/AmazonECS/latest/bestpracticesguide/networking.html) to see if anything relevant to your setup is covered in more detail. It may also be helpful to see if you can successfully complete the [Windows containers getting started tutorial](https://docs.aws.amazon.com/AmazonECS/latest/developerguide/ECS_Windows_getting_started.html) and then compare what configuration was needed there vs. what's in your own VPC/cluster/ task definition. (Apologies in advance if these are resources you've already viewed and exhausted!)
