### ISSUE TITLE
Task definition deployment stuck 

### ISSUE THREAD

**Issue by chillerfx** [aws-actions/amazon-ecs-deploy-task-definition#24]
I'm not sure how to report it but I will try to explain it in detail
I'm Using GitHub action template for AWS ECS deployment.
Everything works fine as long as there is one service definition per cluster.
#### Enter the problem
 I have a multi repo setup where I have defined service and task definitions per one cluster (Service definitions are deployed to ECS).
The first Task definition is deployed with no problems after there's commit to master. The second (different repository) one got stuck and nothing happens (waited at least 10 minutes)

EDIT:
After the second attempt - one service is deployed successfully, and the second deployment timedout after 10 minutes 21s with error `##[error]Resource is not in the state servicesStable`

EDIT2:
Solved by following https://aws.amazon.com/premiumsupport/knowledge-center/cloudformation-ecs-service-stabilize/

**Comment by clareliguori** [comment]
Hi @chillerfx, task definition deployments can fail / time out if containers are not able to launch successfully with the new task definition or if they do not reliably pass load balancer health checks.

Do you have a request to change the behavior of this GitHub Action?
