### ISSUE TITLE
deploying existing/same version

### ISSUE THREAD

**Issue by nparfait-industrie** [aws-actions/amazon-ecs-deploy-task-definition#25]
Is there a way to skip running the step to deploy if the image tag is the same as currently deployed? Currently it looks like it still takes a few minutes to do the deployment even though there are no changes.

The reason for this is i have 2 clusters with approx 15 services. I have 1 deployment repo which will deploy all the services (via a version file which i can update the image tag). However I only want to deploy if the image has changed.

**Comment by clareliguori** [comment]
This action doesn't attempt to de-dupe on any of the task def attributes for deployment, but PRs are welcome!

**Comment by nparfait-industrie** [comment]
thanks, I'll have a go at it next week.
