### ISSUE TITLE
Action failing with error "Unexpected key 'runtimePlatform' found in params"

### ISSUE THREAD

**Issue by jeremysimms** [aws-actions/amazon-ecs-deploy-task-definition#274]
It looks like the task definition json returned `describe-task-definition` now contains the `runtimePlatform` attribute. This is causing builds to break in workflows that fetch the task definition and then mutate them, rather than keep them under version control.

**Comment by chuongtrh** [comment]
Facing the same issue. Looking forward a new version fixed it.

**Comment by Stochastic-Squirrel** [comment]
I can confirm that I am having the same issue

**Comment by hectorgrecco** [comment]
Same issue here.

**Comment by roeeklinger** [comment]
Same issue

**Comment by roeeklinger** [comment]
Same, I did the following workaround (probably not recommended, but it works for now as a hot fix):

```
aws ecs describe-task-definition --task-definition $ECS_SERVICE --query taskDefinition > task-definition.json
sed -i '/runtimePlatform/,+3 d' task-definition.json
```

**Comment by LuisEvilCo** [comment]
I had the same issue and I solved by using the "latest" version of the deploy task definition job.

`uses: aws-actions/amazon-ecs-deploy-task-definition@v1`
