### ISSUE TITLE
Step fails with "Resource is not in the state servicesStable" but new task is running successfully in ECS

### ISSUE THREAD

**Issue by felipe-gdr** [aws-actions/amazon-ecs-deploy-task-definition#30]
I've defined a `aws-actions/amazon-ecs-deploy-task-definition@v1` step on my workflow file, and that step keeps failing:

```
Run aws-actions/amazon-ecs-deploy-task-definition@v1
  with:
    task-definition: /home/runner/work/_temp/task-definition-31660kV60ttYXRWu.json
    service: my-service-staging
    cluster: my-cluster
    wait-for-service-stability: true
  env:
    AWS_ACCESS_KEY_ID: ***
    AWS_SECRET_ACCESS_KEY: ***
    AWS_DEFAULT_REGION: us-east-2
    AWS_REGION: us-east-2
    JAVA_HOME: /opt/hostedtoolcache/jdk/8.0.242/x64
    JAVA_HOME_8.0.242_x64: /opt/hostedtoolcache/jdk/8.0.242/x64
##[error]Resource is not in the state servicesStable
##[error]Node run failed with exit code 1
```

The step hangs for a good 5-10 minutes meanwhile, in ECS I can verify that I have 2 tasks in the `RUNNING` state: the old one and the new one.

After a while, the step fails, but the application is successfully updated in ECS. 

It seems that the step times out while waiting for the service to reach a stable state, which is a desired count of 1. But I'm not 100% sure.

**Comment by felipe-gdr** [comment]
I could fix this by reducing the "Deregistration delay" value from 300 to 30 seconds on the target groups of the NLB associated with my ECS service.

**Comment by ahmednkhan24** [comment]
Hi, I am trying to deploy a simple node API (found [here](https://github.com/ahmednkhan24/node-to-aws)), and I seem to be getting a similar error when trying to use the GithubActions workflow. 

I haven't set up a Load Balancer since it was a demo application, so I was wondering if there could be another solution to fixing this failed build?

As you can see, the build hung for around 30 minutes:

<img width="1091" alt="Screen Shot 2020-04-02 at 6 13 47 PM" src="https://user-images.githubusercontent.com/32524021/78308666-acf5c000-750e-11ea-90f8-7c290dec7544.png">

**Comment by clareliguori** [comment]
@ahmednkhan24 you'll need to look at your service in the ECS console to determine why the deployment did not succeed.  For example, look at the Events tab, and look under "Stopped" tasks in the Tasks tab.

**Comment by BharathDundi1** [comment]
> Hi, I am trying to deploy a simple node API (found [here](https://github.com/ahmednkhan24/node-to-aws)), and I seem to be getting a similar error when trying to use the GithubActions workflow.
> 
> I haven't set up a Load Balancer since it was a demo application, so I was wondering if there could be another solution to fixing this failed build?
> 
> As you can see, the build hung for around 30 minutes:
> 
> <img alt="Screen Shot 2020-04-02 at 6 13 47 PM" width="1091" src="https://user-images.githubusercontent.com/32524021/78308666-acf5c000-750e-11ea-90f8-7c290dec7544.png">

Hey Ahmed, I'm getting the same error as well. Were you able to figure out what is causing this issue?

**Comment by ahmednkhan24** [comment]
Hey, yes I was able to get it to work. Here's [my repo](https://github.com/ahmednkhan24/AWS-ECS-Pipeline), see if there's anything missing from your task-definition.json file compared to mine

**Comment by BharathDundi1** [comment]
Hey Ahmed thank you so much :)

**Comment by AlliNeuman** [comment]
> Deregistration delay

Where did you make this change?

**Comment by thanhn1012** [comment]
@AlliNeuman 
You can changed it in Target group > Attributes 
![image](https://user-images.githubusercontent.com/64126414/193611343-94cba67c-75bb-4ef9-bab2-9257e570dc76.png)
