### ISSUE TITLE
GitHub job times out but task deployment completes successfully

### ISSUE THREAD

**Issue by jzingler-lp** [aws-actions/amazon-ecs-deploy-task-definition#31]
I am running into an issue that causes my job to hang and fail after 10 minutes, however, the task deployment completes successfully. I set the `wait-for-service-stability: true` as part of the config options which I think may be causing the issue. 

Error during deploy:
```
Run aws-actions/amazon-ecs-deploy-task-definition@v1
##[error]Resource is not in the state servicesStable
##[error]Node run failed with exit code 1
```

My environment includes the following components:
`Private Fargate Service`

I would like to use the `wait-for-service-stability: true` so please let me know if you have suggestions to debug or fix. Thanks

**Comment by clareliguori** [comment]
How long does it take for your deployment to complete successfully?  More or less than 10 minutes?

This is how a "stable" service is defined:
https://github.com/aws/aws-sdk-js/blob/cc29728c1c4178969ebabe3bbe6b6f3159436394/apis/ecs-2014-11-13.waiters2.json#L42-L72

For the output of `aws ecs describe-services --services <my service> --cluster <my cluster>`:
* the service exists
* the service is not in "draining" state
* the service is not in "inactive" state
* the number of tasks in "RUNNING" state is equal to the desired count
* the service has a single deployment

**Comment by jzingler-lp** [comment]
Thank you @clareliguori. I was able to resolve the issue. The problem was on my end related to a faulty log group definition in my task definition.

**Comment by maroy1986** [comment]
> Thank you @clareliguori. I was able to resolve the issue. The problem was on my end related to a faulty log group definition in my task definition.
I know it's been a while but, do you remember what you changed in your log group definition to have it working? I'm hitting the exact same issue here and can't solve it. Thanks!

**Comment by SunnGHubX** [comment]
@jzingler-lp I am also running into same issue..  I have also attempted the reset on desired count to zero as well but still problem re-occurs.. What faulty log group definitition was it you fixed or removed from your task definition?  Can you clarify @jzingler-lp ?

**Comment by damusix** [comment]
@clareliguori Running into this issue on every deploy. We get a successful deploy, which takes about 2 minutes, we have a 5 minute grace period, and about 3 minutes after that, the app becomes healthy (10 - 15 min total).... Then github actions timeouts and fails 30 minutes later... Any clues?

**Comment by anitakrueger** [comment]
Was anyone able to solve this? We have the same issue with a deployment that has reached `steady` state in the ECS Events tab shortly before the github action returns with `Error: Resource is not in the state servicesStable`.

**Comment by yadigarbz** [comment]
Hello everyone, I also face this issue and am able to solve it, but unfortunately as the nature of this work I believe(or blame AWS :) there is no specific resolution. But so far I can say you need to make sure your Log config is solid and enabled. In my case I faced after I struggled long with DataDog and Fluentbit - Firelens logs, I corrupted the log config while working on configs. Let me share my task definition so, it may help.
For App Container:
-- Log driver: awsfirelens
-- Base variables: 
```
dd_source | ecs_fargate
dd_tags | project:fluentbit
Name | datadog
```

For DataDog agent:
-- Log driver awslogs
-- Base variables:
```
awslogs-group | /ecs/<my-task-def>
awslogs-region | eu-central-1
awslogs-stream-prefix | ecs
```

For LogRouter(Container that fluentbit config created):
-- No driver, No variable

If I need to compare two conditions in which I sucked up and succeed, the most important diff is I changed all my containers' log config to awslogs regardless if they logging or not, and changed my app container's log config to firelens config. But the thing was logrouter and datadog agent didn't log anything properly, especially about health checks, or doesn't inform the AWS about if your app is up and running unless you configure your app correctly to send logs to datadog agent. The main idea about servicesState sensing as steady must be your apps are logging successfully if they have logconfig, if your container doesn't log, do not add log config
