### ISSUE TITLE
Error: Unsupported deployment controller: ECS

### ISSUE THREAD

**Issue by cristianpaul0** [aws-actions/amazon-ecs-deploy-task-definition#388]
Suddenly my GH action started to throw 

```Error: Unsupported deployment controller: ECS
##[debug]Error: Unsupported deployment controller: ECS
##[debug]    at run (/home/runner/work/_actions/aws-actions/amazon-ecs-deploy-task-definition/v1.4.9/dist/index.js:487:15)
##[debug]    at processTicksAndRejections (internal/process/task_queues.js:97:5)
##[debug]Node Action run completed with exit code 1
##[debug]Finishing: Deploy Amazon ECS task definition```

**Comment by jshah** [comment]
I think it needs a new version deploy that includes the fix from https://github.com/aws-actions/amazon-ecs-deploy-task-definition/pull/387

@dannyrandall

**Comment by dannyrandall** [comment]
You're right - it's been updated https://github.com/aws-actions/amazon-ecs-deploy-task-definition/pull/392 and was just released!😊 Try it out and see if you're still having any issues.

Thank you!
