### ISSUE TITLE
Immediate echo of the CodeDeploy deployment link

### ISSUE THREAD

**Issue by jensenbox** [aws-actions/amazon-ecs-deploy-task-definition#42]
An amazing feature would be to echo back to the user a link to where they can go to watch the deployment in real time.

For Example:

https://us-west-2.console.aws.amazon.com/codesuite/codedeploy/deployments/d-QWI2413HF2?region=us-west-2

**Comment by clareliguori** [comment]
That sounds very useful!

I probably will not be able to get around to adding this immediately, but contributions are welcome if anyone has time :)
