### ISSUE TITLE
Unexpected key 'valueFrom' found in params.containerDefinitions[2].environment[0]

### ISSUE THREAD

**Issue by arifulhb** [aws-actions/amazon-ecs-deploy-task-definition#44]
Hello there,

In my "Deploy Amazon ECS task definition" stage, I get this error. 
```
Unexpected key 'valueFrom' found in params.containerDefinitions[2].environment[0]
```
In my `environment` set I have this
```
"environment": [
      {
        "name": "ssm_test",
        "valueFrom": "arn:aws:ssm:us-xxxx-1:0000000000:parameter/test_name_v1"
      }
]
```
I am using this `valueFrom` as per reference of AWS Support for [Specifying Sensitive Data Using system Manager Parameters Group](https://docs.aws.amazon.com/AmazonECS/latest/developerguide/specifying-sensitive-data-parameters.html)

Is this action does not support `valueFrom`? If yes, is there any chance of future feature?

Thanks
Ariful

**Comment by clareliguori** [comment]
Hello, valueFrom is not valid for the `environment` section.  It should be in the `secrets` section in your task definition, as seen on the doc you linked.
