### ISSUE TITLE
Private repository credentials are not a supported authentication method for ECR repositories.

### ISSUE THREAD

**Issue by ahmednkhan24** [aws-actions/amazon-ecs-deploy-task-definition#48]
I am trying to learn more about AWS, and I really liked the idea of creating my own CI/CD pipeline using GithubActions. 

I saw [this](https://www.youtube.com/watch?v=KJNj37ZXPqE&t=2360s) video posted by AWS Events and wanted to do something similar on my own.

I am trying to use the prebuilt workflow to take a simple node.js api and build, tag, push, and deploy it to my AWS EC2 instance. 

I feel like I set everything up as instructed, but I keep getting this error when triggering my workflow:

<img width="866" alt="Screen Shot 2020-03-31 at 7 33 00 PM" src="https://user-images.githubusercontent.com/32524021/78087412-a50b1400-7386-11ea-8e9c-fe016204fd33.png">

I wrote down how I created my ECR repo and ECS cluster/task in the readme of my project [here](https://github.com/ahmednkhan24/node-to-aws).
Here's what my cluster/tasks look like:

<img width="1174" alt="Screen Shot 2020-03-31 at 7 46 24 PM" src="https://user-images.githubusercontent.com/32524021/78088012-860d8180-7388-11ea-97be-bc39121ed547.png">

Is there any additional setup I need to do to get this workflow working? Do I need to configure a secret? 

Any help is appreciated.

Thanks :)

**Comment by clareliguori** [comment]
That error is telling you that you have private creds set in the task definition, but private creds should not be set if using an ECR image.
https://docs.aws.amazon.com/AmazonECS/latest/developerguide/private-auth.html

Do you have anything set for 'repositoryCredentials' in the task definition file?

**Comment by ahmednkhan24** [comment]
My task-definitions.json file that was auto-generated by the AWS console after I created it using default values has this attribute in it:

```
"repositoryCredentials": {
    "credentialsParameter": ""
}
```

I don't believe I clicked the "Private repository authentication* check box when adding the container to the task definition.
When I log into the AWS console to view my task definition, I see this:

```
{
  "ipcMode": null,
  "executionRoleArn": null,
  "containerDefinitions": [
    {
      "dnsSearchDomains": null,
      "logConfiguration": null,
      "entryPoint": null,
      "portMappings": [
        {
          "hostPort": 80,
          "protocol": "tcp",
          "containerPort": 3000
        }
      ],
      "command": null,
      "linuxParameters": null,
      "cpu": 0,
      "environment": [
        {
          "name": "MYSECRET",
          "value": "my-aws-super-secret"
        }
      ],
      "resourceRequirements": null,
      "ulimits": null,
      "dnsServers": null,
      "mountPoints": [],
      "workingDirectory": null,
      "secrets": null,
      "dockerSecurityOptions": null,
      "memory": 512,
      "memoryReservation": null,
      "volumesFrom": [],
      "stopTimeout": null,
      "image": "848213930039.dkr.ecr.us-east-2.amazonaws.com/aws-sample-nodejs-app:latest",
      "startTimeout": null,
      "firelensConfiguration": null,
      "dependsOn": null,
      "disableNetworking": null,
      "interactive": null,
      "healthCheck": null,
      "essential": true,
      "links": null,
      "hostname": null,
      "extraHosts": null,
      "pseudoTerminal": null,
      "user": null,
      "readonlyRootFilesystem": null,
      "dockerLabels": null,
      "systemControls": null,
      "privileged": null,
      "name": "sample-node-container"
    }
  ],
  "placementConstraints": [],
  "memory": null,
  "taskRoleArn": null,
  "compatibilities": [
    "EC2"
  ],
  "taskDefinitionArn": "arn:aws:ecs:us-east-2:848213930039:task-definition/demo-node-task-definition:1",
  "family": "demo-node-task-definition",
  "requiresAttributes": [
    {
      "targetId": null,
      "targetType": null,
      "value": null,
      "name": "com.amazonaws.ecs.capability.ecr-auth"
    }
  ],
  "pidMode": null,
  "requiresCompatibilities": [
    "EC2"
  ],
  "networkMode": null,
  "cpu": null,
  "revision": 1,
  "status": "ACTIVE",
  "inferenceAccelerators": null,
  "proxyConfiguration": null,
  "volumes": []
}
```

**Comment by clareliguori** [comment]
I put up a PR to fix this, but in the meantime remove the "tags" property from your file as well.

**Comment by ahmednkhan24** [comment]
Awesome, thank you for looking into it! I'll go ahead and close the issue.

**Comment by ahmednkhan24** [comment]
Hi, I saw that your PR was merged and it did not have a fast fail like last time, so thank you. 
However, the deployment to AWS ECS using the task-definition provided still fails after attempting for ~30 minutes. 
H

**Comment by enobrev** [comment]
Just adding - in case anyone else ends up here from the ether - when I moved from a task from a private dockerhub account to a private ECR, I had forgotten to remove `repositoryCredentials` from my task definition.  This was the error I was getting and it wasn't clear why.  Thanks @clareliguori !
