### ISSUE TITLE
Add support for DesiredCount

### ISSUE THREAD

**Issue by romankydybets** [aws-actions/amazon-ecs-deploy-task-definition#499]
Hi Team,
it would be great to have DesiredCount support during deployment.
https://docs.aws.amazon.com/cli/latest/reference/ecs/update-service.html
`--desired-count`

**Comment by mendhak** [comment]
Looks like it's been merged, but not released yet?

https://github.com/aws-actions/amazon-ecs-deploy-task-definition/pull/505

**Comment by romankydybets** [comment]
I completely lost, how to perform release?
