### ISSUE TITLE
updateTaskSet to deploy schedule task

### ISSUE THREAD

**Issue by joshuajiangdev** [aws-actions/amazon-ecs-deploy-task-definition#55]
Hi, I'm trying to use github actions to deploy my change to ECS. Everything is awesome, but right now I can only deploy to ECS service, in my use case I also want to deploy ECS scheduled task.

**Comment by clareliguori** [comment]
Hi, the `service` input is optional, so if you only need to register a task definition, you can provide only the `task-definition` input.  If your scheduled task is using the "latest" task definition (e.g. task def family is specified, but not task def version), then your next task will automatically run with the newly deployed task definition.
https://github.com/aws-actions/amazon-ecs-deploy-task-definition/blob/master/action.yml#L10-L12

**Comment by nulldozer** [comment]
> If your scheduled task is using the "latest" task definition (e.g. task def family is specified, but not task def version), then your next task will automatically run with the newly deployed task definition

It doesn't seem to work that way, at least not in the aws console. Leaving the revision blank, setting it to "latest", or selecting "<number> (latest)" will set it to the latest revision at the time, and it will continue to use that revision going forward.

There doesn't seem to be a way to update a scheduled task with this action or with any other provided by aws.

**Comment by Oldharlem** [comment]
Any news on this?

**Comment by dmgritsan** [comment]
> It doesn't seem to work that way, at least not in the aws console. Leaving the revision blank, setting it to "latest", or selecting e.g. "10 (latest)" will set it to the latest revision at the time, and it will continue to use that revision going forward.

@nulldozer if you edit scheduled task not in ECS Cluster but in CloudWatch rules, you can use true Latest not the latest at the time
![Screenshot 2021-06-21 004234](https://user-images.githubusercontent.com/57149045/122689207-a04fab80-d229-11eb-9dc5-c14c9b44539a.png)

**Comment by datatrigger** [comment]
Many thanks @dmgritsan!
