### ISSUE TITLE
AWS SDK deprecation

### ISSUE THREAD

**Issue by johnseekins-pathccm** [aws-actions/amazon-ecs-deploy-task-definition#551]
Similar to https://github.com/aws-actions/amazon-ecs-deploy-task-definition/issues/535, I'm seeing the following message in my execution logs. Any chance we can upgrade the SDK version?

```
(node:1669) NOTE: The AWS SDK for JavaScript (v2) will enter maintenance mode
on September 8, 2024 and reach end-of-support on September 8, 2025.

Please migrate your code to use AWS SDK for JavaScript (v3).
For more information, check blog post at https://a.co/cUPnyil
(Use `node --trace-warnings ...` to show where the warning was created)
```

**Comment by omkhegde** [comment]
Fixed as part of https://github.com/aws-actions/amazon-ecs-deploy-task-definition/pull/529. This upgrade will be included in the next release.
