### ISSUE TITLE
Upgrade to newer version of AWS Javascript SDK

### ISSUE THREAD

**Issue by AndersonSean** [aws-actions/amazon-ecs-deploy-task-definition#561]
When running the action I get:
Run aws-actions/amazon-ecs-deploy-task-definition@v1
(node:1621) NOTE: The AWS SDK for JavaScript (v2) will enter maintenance mode

Could we please have it upgraded to use the AWS SDK v3

**Comment by amazreech** [comment]
Hi @seana39223, AWS SDK has upgrade change has been made as part of(PR #529)[https://github.com/aws-actions/amazon-ecs-deploy-task-definition/pull/529] & [Issue #551](https://github.com/aws-actions/amazon-ecs-deploy-task-definition/issues/551)

This has not been yet released tho. We will be working on releasing this along with other changes.

Thank you!

**Comment by vishaliamops** [comment]
Hello, Please Release the latest version with updated changes of AWS SDK.

**Comment by cynchealth-doug** [comment]
I see this was merged but we still get the deprecation warning in our github actions. Did the @version change?

**Comment by crrobinson14** [comment]
No they still haven't released it. :( Maybe this is abandonware?

**Comment by karanbokil** [comment]
Appreciate everyone's patience, [v2.0.0](https://github.com/aws-actions/amazon-ecs-deploy-task-definition/releases/tag/v2.0.0) has been released to include AWS SDK v3! Please open new issues if you discover any problems with it.
