### ISSUE TITLE
Broken Examples with ECS Updates

### ISSUE THREAD

**Issue by moloch--** [aws-actions/amazon-ecs-deploy-task-definition#584]
https://aws.amazon.com/about-aws/whats-new/2024/07/amazon-ecs-software-version-consistency-containerized-applications/

This update seems to have broken my deployments, and the examples in this repository. When using the example, ECS attempts to pull the SHA256 from `docker.io` instead of the ECR repository:

```
CannotPullContainerError: pull image manifest has been retried 1 time(s): failed to resolve ref docker.io/library/sha256:8795397484604bc67cfcda4f4245dd248b172df523ce9778209e735ffe370426: pull access denied, repository does not exist or may require authorization: server message: insufficient_scope: authorization failed
```

It doesn't seem you can specify the ECR repository in `image` either, attempting to specify the full URL of the image also fails:

```
Error: Failed to register task definition in ECS: Container.image repository contains invalid characters.
Error: Container.image repository contains invalid characters.
```

**Comment by kg-aws** [comment]
Hi @moloch - We verified that the example in the repository and found that its working as expected. Unfortunately, we can't provide product support over GitHub issues but feel free to contact [Amazon Support](https://aws.amazon.com/contact-us).
