### ISSUE TITLE
v1.6.0: STRING_VALUE cannot be converted to Integer

### ISSUE THREAD

**Issue by opsanatoliy** [aws-actions/amazon-ecs-deploy-task-definition#587]
Hi folks! After the latest update of action, our deployment started to fail with the following error:
`Error: Failed to register task definition in ECS: STRING_VALUE cannot be converted to Integer`

<img width="747" alt="image" src="https://github.com/user-attachments/assets/8db57efe-7acd-409b-9cdb-5aa542ccac3d">

The action itself doesn't say much about which field failed to be converted, but on the v1.5.0 everything works fine. 
Could you please tell me how I can get a debug output from the action so I can post it here.

**Comment by vgouv** [comment]
hello, yes indeed.
It may also be related with https://github.com/aws-actions/amazon-ecs-render-task-definition/blob/v1.4.0/CHANGELOG.md

**Comment by s3cube** [comment]
Thanks for raising this issue! 

We're currently trying to reproduce and investigate the issue on our end.  

As a follow-up to the comment by @vgouv, were you also using v1.4.0 of the `amazon-ecs-render-task-definition` when this error occurred?

**Comment by opsanatoliy** [comment]
We specified the v1 version, so I guess that GitHub Runner downloaded the latest one. The best I can do is give you a hash of the version that was working: `Download action repository 'aws-actions/amazon-ecs-deploy-task-definition@v1' (SHA:69e7aed9b8acdd75a6c585ac669c33831ab1b9a3)`

**Comment by s3cube** [comment]
Thanks! 

Also, would you be able to confirm if the [`memory`](https://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuide/aws-properties-ecs-taskdefinition-containerdefinition.html#cfn-ecs-taskdefinition-containerdefinition-memory)  parameter in the `ContainerDefinition` within the `TaskDefinition` is defined as a string or integer?

**Comment by stamptime** [comment]
Hello! Just as a workaround for this issue specifying version `v1.5.0` resolved the problem for me.
```
...
- uses: aws-actions/amazon-ecs-deploy-task-definition@v1.5.0
...
```

**Comment by s3cube** [comment]
Dropping in an update: We've updated the `tag` that  [`v1`](https://github.com/aws-actions/amazon-ecs-deploy-task-definition/releases/tag/v1)  points to. It now will build against release v.1.5.0 instead of v.1.6.0. 

We'll follow-up with a fix/version-upgrade that addresses the issues in v.1.6.0.

**Comment by s3cube** [comment]
Issue appears to have been introduced as a part of the SDK upgrade from v2 to v3. 

 Type-checking seems to be enforced for the task-definition as a whole for parameters in the task-definition. Tested against `cpu`, `memory`, `containerDefinition.cpu`, `containerDefinition.memory`, `portMappings.hostPort`, `portMappings.containerPort`

**Comment by vgouv** [comment]
for the ref in my case that failed with the new version (1.6.0) the referred fields are:
```
{
  "cpu": "512",
  "memory": "512",
...
"containerDefinitions": [
    {
             "cpu": 0,
             "memoryReservation": 64,
             "portMappings": [
              {
                "containerPort": 8080,
                "hostPort": 0,
```
which seem correct. 


In other task definitions (that I did not test with the 1.6.0), I have
```
  "cpu":  null
```
which also works.

**Comment by karanbokil** [comment]
Appreciate everyone's patience, [v2.0.0](https://github.com/aws-actions/amazon-ecs-deploy-task-definition/releases/tag/v2.0.0) has been released to include AWS SDK v3! As mentioned before, if you cannot make the necessary type changes to your task definition parameters, continue to use the [v1 tag](https://github.com/aws-actions/amazon-ecs-deploy-task-definition/releases/tag/v1). Otherwise, adjust your task definition file to correspond to the [types](https://docs.aws.amazon.com/AmazonECS/latest/developerguide/task_definition_parameters.html) in the task definition schema and update your workflow to use [v2](https://github.com/aws-actions/amazon-ecs-deploy-task-definition/releases/tag/v2). Please open new issues if you discover any problems with it.

**Comment by ZhaoKunLong** [comment]
Yeah, I met it on v1 and upgraded to v2. But it's still there, so I searched here. 
Just as a note, this will work for both v1 / v2
```
{
  "cpu": "512",  // should be string,
  "memory": "512", // should be string
...
"containerDefinitions": [
    portMappings:[
      {
        containerPort: 3000 //  should be int.
       }
    ]
  ]
}
```
