### ISSUE TITLE
Request to update to AWS SDK for JavaScript (v3)

### ISSUE THREAD

**Issue by kkemal** [aws-actions/amazon-ecs-deploy-task-definition#589]
The AWS SDK for JavaScript (v2) will enter maintenance mode on September 8, 2024, and reach end-of-support on September 8, 2025. This action currently uses AWS SDK v2. To ensure continued support and security, please update the action to use AWS SDK for JavaScript (v3).

**Comment by omkhegde** [comment]
Hello @kkemal, thank you for creating this issue. We already have an issue [#561](https://github.com/aws-actions/amazon-ecs-deploy-task-definition/issues/561) to track this. We are currently working on creating a new release which includes the SDK update, so please keep an eye out for that in the upcoming weeks. 

I'm closing this issue in favor of the one already existing([#561](https://github.com/aws-actions/amazon-ecs-deploy-task-definition/issues/561)).
