### ISSUE TITLE
Fargate deployment not working anymore as expected

### ISSUE THREAD

**Issue by bitbreakr** [aws-actions/amazon-ecs-deploy-task-definition#62]
Hello Guys, 

We have been using this Github action for a couple of weeks now, and everything was good.
Since a few days, we are having issues deploying.

We have to manually delete the according running task from AWS ECS console for the job to succeed. Otherwise, deploy get stuck for minutes until an error spawns about a timeout and service stability.

<img width="1099" alt="Screenshot 2020-05-04 at 16 00 25" src="https://user-images.githubusercontent.com/3123986/80975414-5ab40180-8e22-11ea-8820-964badfc2a4d.png">

Is there something we have missed out during configuration?

We currently have 4 clusters:

* Develop
* Demo
* Staging
* Production

Each cluster run the 3 same tasks & use the same task-definition.json -> can it be the issue?

Thanks in advance

**Comment by allisaurus** [comment]
Hi @bitbreakr - did you make any changes to how you're using the action between when it was working and when problems started? Also, could you provide the (redacted, where appropriate) YML file where you're invoking the action? Thanks!

**Comment by allisaurus** [comment]
You may also want to check in the ECS console for the specific reason why the service deployment(s) didn't work. Here's some info on [where to look](https://github.com/aws-actions/amazon-ecs-deploy-task-definition/issues/30#issuecomment-608463714), if it's unclear.

**Comment by pkandasamy91** [comment]
@bitbreakr are you still experiencing this error?

**Comment by pkandasamy91** [comment]
Closing, feel free to reopen if this is still an issue.

**Comment by espoirMur** [comment]
Getting the same issue, I am also using GitHub actions to deploy

**Comment by espoirMur** [comment]
Here is what I am getting about when. I run the command :

`aws ecs describe-services --cluster [CLUSTER] --services [SERVICE]`


```
{
    "services": [
        {
            "serviceArn": "arn:aws:ecs:us-east-2:xxxxxxxx:service/xxxxxxxx-cluster/xxxxxxxx-service",
            "serviceName": "xxxxxxxx-service",
            "clusterArn": "arn:aws:ecs:us-east-2:xxxxxxxx:cluster/xxxxxxxx-cluster",
            "loadBalancers": [],
            "serviceRegistries": [],
            "status": "ACTIVE",
            "desiredCount": 1,
            "runningCount": 1,
            "pendingCount": 1,
            "launchType": "FARGATE",
            "platformVersion": "LATEST",
            "taskDefinition": "arn:aws:ecs:us-east-2:xxxxxxxx:task-definition/xxxxxxxx-task-definition:6",
            "deploymentConfiguration": {
                "maximumPercent": 200,
                "minimumHealthyPercent": 50
            },
            "deployments": [
                {
                    "id": "ecs-svc/8262972806176612824",
                    "status": "PRIMARY",
                    "taskDefinition": "arn:aws:ecs:us-east-2:xxxxxxxx:task-definition/xxxxxxxx-task-definition:6",
                    "desiredCount": 1,
                    "pendingCount": 1,
                    "runningCount": 0,
                    "createdAt": "2021-01-29T11:34:50.183000+02:00",
                    "updatedAt": "2021-01-29T20:11:32.942000+02:00",
                    "launchType": "FARGATE",
                    "platformVersion": "1.3.0",
                    "networkConfiguration": {
                        "awsvpcConfiguration": {
                            "subnets": [
                                "subnet-08c0c4477f057c6cf",
                                "subnet-07d0d491b714e9336"
                            ],
                            "securityGroups": [
                                "sg-06c1965509be40629"
                            ],
                            "assignPublicIp": "DISABLED"
                        }
                    }
                },
                {
                    "id": "ecs-svc/1598104970275877557",
                    "status": "ACTIVE",
                    "taskDefinition": "arn:aws:ecs:us-east-2:xxxxxxxx:task-definition/xxxxxxxx-task-definition:3",
                    "desiredCount": 1,
                    "pendingCount": 0,
                    "runningCount": 1,
                    "createdAt": "2021-01-28T21:49:29.575000+02:00",
                    "updatedAt": "2021-01-29T10:46:14.651000+02:00",
                    "launchType": "FARGATE",
                    "platformVersion": "1.3.0",
                    "networkConfiguration": {
                        "awsvpcConfiguration": {
                            "subnets": [
                                "subnet-08c0c4477f057c6cf",
                                "subnet-07d0d491b714e9336"
                            ],
                            "securityGroups": [
                                "sg-06c1965509be40629"
                            ],
                            "assignPublicIp": "DISABLED"
                        }
                    }
                }
            ],
            "roleArn": "arn:aws:iam::xxxxxxxx:role/aws-service-role/ecs.amazonaws.com/AWSServiceRoleForECS",
            "events": [
                {
                    "id": "d35836d0-4e0b-46f3-9644-06af41d78bd1",
                    "createdAt": "2021-01-29T20:11:33.162000+02:00",
                    "message": "(service xxxxxxxx-service) has started 1 tasks: (task 95e54380ac4d46479d110006a40b3f61)."
                },
                {
                    "id": "c21f5e69-1851-4b89-bb20-876350182c5a",
                    "createdAt": "2021-01-29T20:09:43.390000+02:00",
                    "message": "(service xxxxxxxx-service) has started 1 tasks: (task e563ee8d51b94ab1bd843834370dc483)."
                },
              # this is repeatded n tiimes
            "createdAt": "2021-01-28T21:49:29.575000+02:00",
            "placementConstraints": [],
            "placementStrategy": [],
            "networkConfiguration": {
                "awsvpcConfiguration": {
                    "subnets": [
                        "subnet-08c0c4477f057c6cf",
                        "subnet-07d0d491b714e9336"
                    ],
                    "securityGroups": [
                        "sg-06c1965509be40629"
                    ],
                    "assignPublicIp": "DISABLED"
                }
            },
            "schedulingStrategy": "REPLICA",
            "createdBy": "arn:aws:iam::xxxxxxxx:user/Espoir.Murhabazi",
            "enableECSManagedTags": false,
            "propagateTags": "NONE"
        }
    ],
    "failures": []
}

```

**Comment by piradeepk** [comment]
@espoirMur are you able to log into the AWS console to see the reason for why your task was stopped (if you click on the Service within the ECS console, there's a stopped tasks tab).

**Comment by bitbreakr** [comment]
@allisaurus sorry for the delay. It has been a while and as far I can recall there was an issue with the Json file. Some values props should not be there or set has null. Kinda retarded.

**Comment by kaka-ruto** [comment]
I have the same issue. This is the stopped reason on the AWS console:

`CannotPullContainerError: inspect image has been retried 1 time(s): failed to resolve ref "ghcr.io/user-name/repo:sha": failed to authorize: failed to fetch anonymous token: unexpected sta...`

**Comment by allisaurus** [comment]
@kaka-ruto according to the error message the ECS agent was not authorized to pull the image. If this is a private repo, you need to provide ECS with a credentials secret to use while pulling it down. See Amazon ECS [private registry authorization](https://docs.aws.amazon.com/AmazonECS/latest/developerguide/private-auth.html) for more info.

**Comment by allisaurus** [comment]
Closing this issue as so far the surfaced problems do not seem to be related to this GitHub Action specifically, but kind of a mixed bag of general ECS deployment errors. If you found yourself here via search or some other method, please take a look at the below docs which may help debug or solve your issue before reopening this or cutting a new one.

* [Checking stopped tasks for errors](https://docs.aws.amazon.com/AmazonECS/latest/developerguide/stopped-task-errors.html)
* ['CannotPullContainer' task errors](https://docs.aws.amazon.com/AmazonECS/latest/developerguide/task_cannot_pull_image.html)
* [Amazon ECS task stuck in pending](https://aws.amazon.com/premiumsupport/knowledge-center/ecs-tasks-stuck-pending-state/)
* [General Amazon ECS troubleshooting guide](https://docs.aws.amazon.com/AmazonECS/latest/developerguide/troubleshooting.html)

**Comment by kaka-ruto** [comment]
Thanks @allisaurus ! That does help. Will it be easier if this Github action provides an easier way to login to other private registries apart from AWS and Docker hub? I find Amazon's [private registry authorization](https://docs.aws.amazon.com/AmazonECS/latest/developerguide/private-auth.html) pretty daunting :(

**Comment by allisaurus** [comment]
@kaka-ruto Unfortunately, this action can't do much to facilitate logging in to or retrieving private registry images b/c its the ECS agent, running on Fargate or EC2, which must be authorized to login and pull the image from your private registry in order to start your container. This action can really only pass _references_ to the container image and the registry creds (via task definition fields) to ECS so that can happen. (Maybe a secrets manger action which would help with the creation of these resources could further help?)

The official docs do look a bit daunting, but using a private image on ECS really just boils down to 3 things:

1. Put the registry credentials for your private repo into an AWS Secrets Manager secret
2. Add permission to retrieve the secret to your ECS task execution role
3. Add a reference to the secret into your task def for the container that needs the private image.

Here's [blog post](https://aws.amazon.com/blogs/compute/introducing-private-registry-authentication-support-for-aws-fargate/) that goes through how to do this in more step-by-step way. Hopefully this helps some!

**Comment by kaka-ruto** [comment]
Thanks a lot for your thoughtful answer and references @allisaurus . It makes the process a little less daunting. Will try them out. Truly appreciate ❤️
