### ISSUE TITLE
Unexpected key 'environmentFiles' : Failed to register task definition in ECS

### ISSUE THREAD

**Issue by gaurav-agarwal27** [aws-actions/amazon-ecs-deploy-task-definition#64]
Using `aws-actions/amazon-ecs-deploy-task-definition@v1`
I have added environmentFiles in my containerDefinitions of `task-definition.json` as:
```
"environmentFiles": [{
    "type": "s3",
    "value": "arn:aws:s3:::ltl-environments/.stg.env"
}],
```
Getting the following error: 
```
##[error]Failed to register task definition in ECS: There were 5 validation errors:
* UnexpectedParameter: Unexpected key 'environmentFiles' found in params.containerDefinitions[0]
* UnexpectedParameter: Unexpected key 'environmentFiles' found in params.containerDefinitions[2]
* UnexpectedParameter: Unexpected key 'environmentFiles' found in params.containerDefinitions[3]
* UnexpectedParameter: Unexpected key 'environmentFiles' found in params.containerDefinitions[4]
* UnexpectedParameter: Unexpected key 'environmentFiles' found in params.containerDefinitions[5]```

**Comment by pkandasamy91** [comment]
It looks like it might be using an older version of the AWS SDK which does not yet support environmentFiles. Will confirm and provide more details.

**Comment by gaurav-agarwal27** [comment]
Thanks @pkandasamy91 , also I am not sure if the latest version of AWS SDK supports `environmentFiles` yet ?

**Comment by clareliguori** [comment]
Hi @gaurav-agarwal27, that feature is not fully released yet, which is why it isn't yet in the SDK.  Please watch this roadmap issue for updates on when it is released: 
https://github.com/aws/containers-roadmap/issues/371

**Comment by gaurav-agarwal27** [comment]
Thanks for the update @clareliguori

**Comment by pkandasamy91** [comment]
Hi @gaurav-agarwal27, support for environmentFiles have now been released: https://aws.amazon.com/about-aws/whats-new/2020/05/amazon-elastic-container-service-supports-environment-files-ec2-launch-type/

The AWS-SDK v2.679.0 now supports environmentFiles: https://github.com/aws/aws-sdk-js/blob/master/CHANGELOG.md

**Comment by pkandasamy91** [comment]
@gaurav-agarwal27 the dependencies have been updated, and you should now be able to use environmentFiles. Let me know if you're still running into issues.

**Comment by gaurav-agarwal27** [comment]
@pkandasamy91 thank you so much for the prompt action. Everything is working fine now 😃
Closing the issue.

**Comment by spencer-shake** [comment]
I'm currently having this same issue, except with `enableFaultInjection`, which is getting automatically added to the task-definition by this process. 
<img width="1336" alt="image" src="https://github.com/user-attachments/assets/8b14cc72-ea96-4aa5-a5ef-322533eb0b1c" />

**Comment by edbentinck** [comment]
> I'm currently having this same issue, except with `enableFaultInjection`, which is getting automatically added to the task-definition...

Same here. In my case I solved it by upgrading from `v1` to `v2`: `aws-actions/amazon-ecs-deploy-task-definition@v2`

**Comment by spencer-shake** [comment]
> > I'm currently having this same issue, except with `enableFaultInjection`, which is getting automatically added to the task-definition...
> 
> Same here. In my case I solved it by upgrading from `v1` to `v2`: `aws-actions/amazon-ecs-deploy-task-definition@v2`

Just came back here to say the same thing. Bumping to v2 worked for me as well

**Comment by Ahmad-anility** [comment]
We are on v2. We have been on v2 for a long time but suddenly started to get this error

**Comment by ereid7** [comment]
@piradeepk This issue should be reopened. We started experiencing the error mentioned in https://github.com/aws-actions/amazon-ecs-deploy-task-definition/issues/64#issuecomment-2578323526 with no changes on our end. Upgrading to aws-actions/amazon-ecs-deploy-task-definition@v2 fixed the issue.
