### ISSUE TITLE
Can I use an existing task-definition instead of creating new?

### ISSUE THREAD

**Issue by DIMPLY** [aws-actions/amazon-ecs-deploy-task-definition#70]
I'm going to use the same task definition each time, just redeploying the task. Is there a way to do this?

**Comment by gaurav-agarwal27** [comment]
@DIMPLY - I have the same question, on every deployment a new revision is created of the task-definition. 
Did you find anything on this? Or is there anything wrong in the configuration?

**Comment by individual11** [comment]
Why was this closed? @DIMPLY you figure it out, or bale and grab a different solution? I know you can run AWS CLI right within the action, but that's messy.
